SELECT * FROM CLIENT
SELECT * FROM RENTAL
SELECT * FROM DISTRICT

INSERT INTO CLIENT VALUES ('One', '1','김종현','010-1111-1111')
INSERT INTO CLIENT VALUES ('Two', '2','김지윤','010-2222-2222')
INSERT INTO CLIENT VALUES ('Three', '3','백설','010-3333-3333')
ALTER TABLE CLIENT ADD PAYMENT VARCHAR2(20)


drop table DISTRICT cascade constraints; 
drop table TOWN cascade constraints; 
drop table CYCLE cascade constraints; 
drop table RENTAL cascade constraints; 
drop table RETURN cascade constraints; 
drop table PAYMENT cascade constraints; 



CREATE TABLE DISTRICT(
	D_NUMBER VARCHAR2(15),
	D_NAME VARCHAR2(15),
	
	CONSTRAINT D_NUMBER_PK PRIMARY KEY(D_NUMBER)
)

CREATE TABLE TOWN(
	T_NUMBER VARCHAR2(15),
	T_NAME VARCHAR2(15),
	D_NUMBER VARCHAR2(15),
	
	CONSTRAINT T_NUMBER_PK PRIMARY KEY(T_NUMBER),
	CONSTRAINT D_NUMBER_FK FOREIGN KEY(D_NUMBER) REFERENCES DISTRICT(D_NUMBER)
)

CREATE TABLE CYCLE(
	C_NUMBER VARCHAR2(15),
	C_NAME VARCHAR2(15),
	C_STATE VARCHAR2(25),
	
	CONSTRAINT C_NUMBER_PK PRIMARY KEY(C_NUMBER) 
)

CREATE TABLE RENTAL(
	R_NUMBER number(15),
	ID VARCHAR2(15),
	D_NUMBER VARCHAR2(15),
	T_NUMBER VARCHAR2(15),
	C_NUMBER VARCHAR2(15),
	R_STATE VARCHAR2(25),
	
	CONSTRAINT R_NUMBER_PK PRIMARY KEY(R_NUMBER),
	CONSTRAINT ID_FK FOREIGN KEY(ID) REFERENCES CLIENT(ID),
	CONSTRAINT D_NUMBER_RFK FOREIGN KEY(D_NUMBER) REFERENCES DISTRICT(D_NUMBER),
	CONSTRAINT T_NUMBER_RFK FOREIGN KEY(T_NUMBER) REFERENCES TOWN(T_NUMBER),
	CONSTRAINT C_NUMBER_RFK FOREIGN KEY(C_NUMBER) REFERENCES CYCLE(C_NUMBER)
)

ALTER TABLE RENTAL MODIFY R_STATE VARCHAR2(25)
ALTER TABLE RENTAL ADD RENTAL_DATE DATE

CREATE SEQUENCE RENTALSEQ
INCREMENT BY 1
START WITH 1
MAXVALUE 10000

CREATE TABLE RETURN(
	RETURN_ID VARCHAR2(15),
	R_NUMBER number(15),
	RETURN_DATE DATE,
	
	CONSTRAINT RETURN_ID_PK PRIMARY KEY(RETURN_ID),
	CONSTRAINT R_NUMBER_FK FOREIGN KEY(R_NUMBER) REFERENCES RENTAL(R_NUMBER)
)

CREATE TABLE PAYMENT(
	P_NUMBER NUMBER(10),
	PRICE NUMBER(15),
	
	CONSTRAINT P_NUMBER_PK PRIMARY KEY(P_NUMBER)
)


CREATE TABLE datetime(
	rental_date VARCHAR2(20),
	return_date VARCHAR2(20)
)






INSERT INTO datetime VALUES('2020-06-25','2020-07-02')

SELECT * FROM DISTRICT
SELECT * FROM TOWN
SELECT * FROM CYCLE
SELECT * FROM RENTAL
SELECT * FROM datetime

INSERT INTO DISTRICT VALUES ('D1', '강남구')
INSERT INTO DISTRICT VALUES ('D2', '광진구')
INSERT INTO DISTRICT VALUES ('D3', '서대문구')
INSERT INTO DISTRICT VALUES ('D4', '서초구')
INSERT INTO DISTRICT VALUES ('D5', '영등포구')

INSERT INTO TOWN VALUES ('T1', '수서동','D1')
INSERT INTO TOWN VALUES ('T2', '청담동', 'D1')
INSERT INTO TOWN VALUES ('T3', '대치동', 'D1')
INSERT INTO TOWN VALUES ('T4', '양재동', 'D4')
INSERT INTO TOWN VALUES ('T5', '내곡동', 'D4')

INSERT INTO CYCLE VALUES ('C1', 'CYCLE1','대여중')
INSERT INTO CYCLE VALUES ('C2', 'CYCLE2','대여기다리는중')
INSERT INTO CYCLE VALUES ('C3', 'CYCLE3','대여기다리는중')

SELECT * FROM RETURN
DELETE RETURN WHERE R_NUMBER = 1

SELECT * FROM RENTAL
INSERT INTO RENTAL VALUES (RENTALSEQ.NEXTVAL,'One','D1','T1','C2','대여기다리는중')
INSERT INTO RENTAL VALUES (RENTALSEQ.NEXTVAL,'One','D1','T1','C2','대여기다리는중','2020-06-25')
DELETE RENTAL WHERE R_NUMBER = 1
INSERT INTO RETURN
VALUES (1, 1, '20/06/20')

SELECT * FROM CLIENT
UPDATE CLIENT SET PAYMENT = '7일' WHERE ID = 'One'

INSERT INTO RENTAL VALUES()
