CREATE TABLE CYCLE_BCYCL (
	BCYCL_NMBR NUMBER PRIMARY KEY,
	BCYCL_STATE VARCHAR2(15)
)

SELECT * FROM CYCLE_BCYCL

DROP TABLE RENTAL

CREATE TABLE RENTAL (
	RENTAL_NMBR NUMBER ,
	RENTAL_TIME TIMESTAMP,
	BCYCL_NMBR NUMBER,
	
	CONSTRAINT BCYCL_NMBR_FK FOREIGN KEY(BCYCL_NMBR) REFERENCES CYCLE_BCYCL(BCYCL_NMBR),
	CONSTRAINT RENTAL_NMBR_PK PRIMARY KEY(RENTAL_NMBR)
	)
	
SELECT * FROM RENTAL

CREATE TABLE CLIENT(
	ID VARCHAR2(15),
	PW VARCHAR2(15),
	NAME VARCHAR2(15),
	PN VARCHAR2(15),
	RENTAL_NMBR,
	
	CONSTRAINT RENTAL_NMBR_FK FOREIGN KEY(RENTAL_NMBR) REFERENCES RENTAL(RENTAL_NMBR),
	CONSTRAINT ID_PK PRIMARY KEY(ID)
)

SELECT * FROM CLIENT

CREATE TABLE RTRN (
	RTRN_TIME TIMESTAMP,
	PAY_STT VARCHAR2(10),
	
	CONSTRAINT RTRN_TIME_PK PRIMARY KEY(RTRN_TIME)
)

SELECT * FROM RTRN

CREATE TABLE PRICE (
	TIMEPRICE NUMBER,
	DAYPRICE NUMBER,
	WEEKPRICE NUMBER,
	MONTHPRICE NUMBER, 
	YEARSPRICE NUMBER
) 

SELECT * FROM PRICE


CREATE TABLE PAYMENT (
	PAY_STT VARCHAR2(10),
	RENTAL_TIME TIMESTAMP,
	RTRN_TIME TIMESTAMP,
	TICKETTYPE VARCHAR2(15),
	RTRN_NMBR NUMBER
)

SELECT * FROM PAYMENT

CREATE TABLE LOCATION (
	RENTAL_OFFICE VARCHAR2(20),
	RTRN_OFFICE VARCHAR2(20),
	LOCATION_NMBR NUMBER,
	LOCATION_CODE VARCHAR2(10),
	CTOC_CODE VARCHAR2(10)
	)

SELECT * FROM LOCATION

CREATE TABLE STATUS (
	RENTAL_OFFICE VARCHAR2(20),
	RTRN_OFFICE VARCHAR2(20),
	CTOC_CODE VARCHAR2(10),
	BCYCL_NMBR NUMBER
)

SELECT * FROM STATUS

DROP TABLE CLIENT

CREATE TABLE CLIENT(
	ID VARCHAR2(15),
	PW VARCHAR2(15),
	NAME VARCHAR2(15),
	PN VARCHAR2(15),
	
	CONSTRAINT ID_PK PRIMARY KEY(ID)
)
SELECT * FROM CLIENT

DROP TABLE STATUS
DROP TABLE LOCATION
DROP TABLE CYCLE_BCYCL
DROP TABLE PAYMENT
DROP TABLE PRICE
DROP TABLE RTRN
DROP TABLE RENTAL

CREATE TABLE CYCLE_BCYCL (
	BCYCL_NMBR NUMBER,
	BCYCL_STATE VARCHAR2(15),

	CONSTRAINT BCYCL_NMBR_PK PRIMARY KEY(BCYCL_NMBR)
	)
	
CREATE TABLE RENTAL (
	RENTAL_NMBR NUMBER,
	RENTAL_TIME TIMESTAMP,
	RTRN_TIME TIMESTAMP,
	LOCATION_CODE VARCHAR2(15),
	BCYCLS_NMBR NUMBER,
	RENTAL_OFFICE VARCHAR2(15),
	RTRN_OFFICE VARCHAR2(15),
	PAY_STT VARCHAR2(10),
	TICKETTYPE VARCHAR2(15),
	RTRN_NMBR NUMBER,
	PAY_NMBR NUMBER,
	BCYCL_NMBR NUMBER,
	TIME_TICKET NUMBER,
	WEEK_TICKET NUMBER,
	MONTH_TICKET NUMBER,
	YEAR_TICKET NUMBER,
	PRICE NUMBER,
)


=